//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PablaAccountingAndTaxServicesDLL.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FilePersonalTax
    {
        public long FilePersonalTaxId { get; set; }
        public Nullable<bool> IsExisting { get; set; }
        public string Firstname { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string SIN { get; set; }
        public string DateOfBirth { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string MaritalStatus { get; set; }
        public string Sex { get; set; }
        public string CurrentAddress { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string PostalCode { get; set; }
        public string NameOfSpouseFirstName { get; set; }
        public string NameOfSpouseMiddleName { get; set; }
        public string NameOfSpouseLastName { get; set; }
        public string SpouseSIN { get; set; }
        public string SpouseDateOfBirth { get; set; }
        public string Children1Name { get; set; }
        public string Children1DateOfBirth { get; set; }
        public string Children2Name { get; set; }
        public string Children2DateOfBirth { get; set; }
        public string Children3Name { get; set; }
        public string Children3DateOfBirth { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
